version: "3.7"
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 9000:9000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    #restart: always
  nginx-lua:
    image: fabiocicerchia/nginx-lua:latest
    container_name: nginx-lua
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./sources_front/:/path/sources_front/
    depends_on:
      - portainer
volumes:
  portainer_data:
